set(CMAKE_SYSTEM_NAME Android)

set(CMAKE_ANDROID_NDK $ENV{ANDROID_NDK_HOME})
set(ANDROID_ABI "arm64-v8a")
set(CMAKE_ANDROID_ARCH_ABI "arm64-v8a")
set(ANDROID_NATIVE_API_LEVEL 28)
set(CMAKE_ANDROID_API 28)
set(ANDROID_TOOLCHAIN clang++)

set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
