
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_CXX_STANDARD 14)

if (TARGET_OS STREQUAL "linux")
  set(COMMON_FLAGS -fno-omit-frame-pointer)
  list(APPEND COMMON_FLAGS -Werror)
  list(APPEND COMMON_FLAGS -fno-strict-aliasing)
  list(APPEND COMMON_FLAGS -D_XOPEN_SOURCE=700)
  list(APPEND COMMON_FLAGS -Wall)
  list(APPEND COMMON_FLAGS -Wextra)
  list(APPEND COMMON_FLAGS -Wunreachable-code)
  list(APPEND COMMON_FLAGS -Wno-unused-function)

  set(DEBUG_OPTION -fno-var-tracking)
  list(APPEND DEBUG_OPTION -fno-inline)
  list(APPEND DEBUG_OPTION -Wshadow)
  list(APPEND DEBUG_OPTION -Wno-error)

  list(APPEND MEM_CHECK_OPTION -fstack-protector-strong)

  if (NOT CMAKE_BUILD_TYPE)
      set(CMAKE_BUILD_TYPE "RelWithDebInfo")
  endif()
  message("CMAKE_BUILD_TYPE = '${CMAKE_BUILD_TYPE}'")

  if(CMAKE_BUILD_TYPE STREQUAL "Debug")
      string(REPLACE " " ";" COMPILE_DEFAULT_FLAGS ${CMAKE_CXX_FLAGS_DEBUG})
      set(CXX_COMPILE_FLAGS ${COMMON_FLAGS} ${DEBUG_OPTION} ${MEM_CHECK_OPTION} ${COMPILE_DEFAULT_FLAGS})
  elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
      string(REPLACE " " ";" COMPILE_DEFAULT_FLAGS ${CMAKE_CXX_FLAGS_RELEASE})
      set(CXX_COMPILE_FLAGS ${COMMON_FLAGS} ${MEM_CHECK_OPTION} ${COMPILE_DEFAULT_FLAGS})
  elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
      string(REPLACE " " ";" COMPILE_DEFAULT_FLAGS ${CMAKE_CXX_FLAGS_RELWITHDEBINFO})
      set(CXX_COMPILE_FLAGS ${COMMON_FLAGS} ${MEM_CHECK_OPTION} ${COMPILE_DEFAULT_FLAGS})
  elseif(CMAKE_BUILD_TYPE STREQUAL "MinSizeRel")
      string(REPLACE " " ";" COMPILE_DEFAULT_FLAGS ${CMAKE_CXX_FLAGS_MINSIZEREL})
      set(CXX_COMPILE_FLAGS ${COMMON_FLAGS} ${MEM_CHECK_OPTION} ${COMPILE_DEFAULT_FLAGS})
  endif()

  set(CXX_LINK_FLAGS  ${MEM_CHECK_OPTION})
endif()
